"""empty message

Revision ID: 2893736abf82
Revises: 4746d5353df9
Create Date: 2019-05-09 18:26:45.009502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2893736abf82'
down_revision = '4746d5353df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourited_waifu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favourited_waifu_character_name'), 'favourited_waifu', ['character_name'], unique=False)
    op.create_index(op.f('ix_favourited_waifu_order'), 'favourited_waifu', ['order'], unique=False)
    op.create_index(op.f('ix_favourited_waifu_user_id'), 'favourited_waifu', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favourited_waifu_user_id'), table_name='favourited_waifu')
    op.drop_index(op.f('ix_favourited_waifu_order'), table_name='favourited_waifu')
    op.drop_index(op.f('ix_favourited_waifu_character_name'), table_name='favourited_waifu')
    op.drop_table('favourited_waifu')
    # ### end Alembic commands ###
