"""empty message

Revision ID: 4746d5353df9
Revises: b400e1a221ed
Create Date: 2019-05-08 20:50:36.913964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4746d5353df9'
down_revision = 'b400e1a221ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_waifu_battles_loser_name'), 'waifu_battles', ['loser_name'], unique=False)
    op.create_index(op.f('ix_waifu_battles_winner_name'), 'waifu_battles', ['winner_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waifu_battles_winner_name'), table_name='waifu_battles')
    op.drop_index(op.f('ix_waifu_battles_loser_name'), table_name='waifu_battles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###
