"""empty message

Revision ID: 4a29fc6a553c
Revises: de7e464a7b7f
Create Date: 2019-05-18 19:57:54.770392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a29fc6a553c'
down_revision = 'de7e464a7b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('api_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_token_expiry')
    op.drop_column('users', 'api_token')
    # ### end Alembic commands ###
