"""inital migration

Revision ID: 784efa1ae3ea
Revises: 
Create Date: 2021-04-25 17:28:21.218880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784efa1ae3ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('api_token', sa.String(), nullable=True),
    sa.Column('api_token_expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('favourited_waifu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favourited_waifu_character_name'), 'favourited_waifu', ['character_name'], unique=False)
    op.create_index(op.f('ix_favourited_waifu_order'), 'favourited_waifu', ['order'], unique=False)
    op.create_index(op.f('ix_favourited_waifu_user_id'), 'favourited_waifu', ['user_id'], unique=False)
    op.create_table('waifu_battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('winner_name', sa.String(), nullable=False),
    sa.Column('loser_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waifu_battles_loser_name'), 'waifu_battles', ['loser_name'], unique=False)
    op.create_index(op.f('ix_waifu_battles_winner_name'), 'waifu_battles', ['winner_name'], unique=False)
    op.create_table('elo_ranking_calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('latest_battle_id', sa.Integer(), nullable=False),
    sa.Column('rankings', sa.String(), nullable=False),
    sa.Column('algorithim_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['latest_battle_id'], ['waifu_battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elo_ranking_calculation_latest_battle_id'), 'elo_ranking_calculation', ['latest_battle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elo_ranking_calculation_latest_battle_id'), table_name='elo_ranking_calculation')
    op.drop_table('elo_ranking_calculation')
    op.drop_index(op.f('ix_waifu_battles_winner_name'), table_name='waifu_battles')
    op.drop_index(op.f('ix_waifu_battles_loser_name'), table_name='waifu_battles')
    op.drop_table('waifu_battles')
    op.drop_index(op.f('ix_favourited_waifu_user_id'), table_name='favourited_waifu')
    op.drop_index(op.f('ix_favourited_waifu_order'), table_name='favourited_waifu')
    op.drop_index(op.f('ix_favourited_waifu_character_name'), table_name='favourited_waifu')
    op.drop_table('favourited_waifu')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('locks')
    # ### end Alembic commands ###
