"""empty message

Revision ID: dbd25bb3e82b
Revises: f416a60b44df
Create Date: 2019-05-13 18:56:20.387691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd25bb3e82b'
down_revision = 'f416a60b44df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo_ranking_calclation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('latest_battle_id', sa.Integer(), nullable=False),
    sa.Column('rankings', sa.String(), nullable=False),
    sa.Column('algorithim_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['latest_battle_id'], ['waifu_battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elo_ranking_calclation_latest_battle_id'), 'elo_ranking_calclation', ['latest_battle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elo_ranking_calclation_latest_battle_id'), table_name='elo_ranking_calclation')
    op.drop_table('elo_ranking_calclation')
    # ### end Alembic commands ###
