"""empty message

Revision ID: de7e464a7b7f
Revises: bfadd4ebe86d
Create Date: 2019-05-14 20:37:12.170911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7e464a7b7f'
down_revision = 'bfadd4ebe86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo_ranking_calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('latest_battle_id', sa.Integer(), nullable=False),
    sa.Column('rankings', sa.String(), nullable=False),
    sa.Column('algorithim_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['latest_battle_id'], ['waifu_battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elo_ranking_calculation_latest_battle_id'), 'elo_ranking_calculation', ['latest_battle_id'], unique=False)
    op.drop_index('ix_elo_ranking_calclation_latest_battle_id', table_name='elo_ranking_calclation')
    op.drop_table('elo_ranking_calclation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo_ranking_calclation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('latest_battle_id', sa.INTEGER(), nullable=False),
    sa.Column('rankings', sa.VARCHAR(), nullable=False),
    sa.Column('algorithim_hash', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['latest_battle_id'], ['waifu_battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_elo_ranking_calclation_latest_battle_id', 'elo_ranking_calclation', ['latest_battle_id'], unique=False)
    op.drop_index(op.f('ix_elo_ranking_calculation_latest_battle_id'), table_name='elo_ranking_calculation')
    op.drop_table('elo_ranking_calculation')
    # ### end Alembic commands ###
